package de.rsev.minecraft.forge.controller.lua.tools.documentation;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generiert die zentrale Index-Datei für die Lua-Dokumentation.
 *
 * Erstellt:
 * docs/Index.md
 *
 * Inhalt:
 * - Titel
 * - Beschreibung
 * - Liste aller Lua-Module
 * - Anzahl der dokumentierten Methoden je Modul
 */
public class LuaIndexGenerator {

    /**
     * Erzeugt oder überschreibt die Index.md.
     *
     * @param docsDir Zielverzeichnis der Dokumentation
     * @throws IOException falls Schreiben/Erstellen fehlschlägt
     */
    public static void generate(Path docsDir) throws IOException {

        // Sicherstellen, dass das Dokumentationsverzeichnis existiert
        Files.createDirectories(docsDir);

        // Pfad zur Index-Datei
        Path indexFile = docsDir.resolve("Index.md");

        // StringBuilder für den Markdown-Inhalt
        StringBuilder builder = new StringBuilder();

        // Titel der Dokumentation
        builder.append("# Lua API Documentation\n\n");

        // Kurzbeschreibung
        builder.append("Automatisch generierte Übersicht aller Lua Module.\n\n");

        builder.append("## Modules\n\n");

        // Alle registrierten Module + Methoden abrufen
        /* 
        Map<LuaDocModule, java.util.List<LuaMethodDoc>> modules =
            LuaDocumentationRegistry.getAll(); 
        */

        // Über alle bekannten Module iterieren (Enum-basierend)
        for (LuaDocModule module : LuaDocModule.values()) {

            // Markdown-Link zur Modul-Dokumentation
            builder.append("- [")
                   .append(module.displayName())   // Anzeigename
                   .append("](")
                   .append(module.displayName())   // Dateiname
                   .append(".md)");

            // Anzahl der Methoden im Modul ermitteln
            int count = LuaDocumentationRegistry.get(module).size();

            // Methodenanzahl anhängen
            builder.append(" — ")
                   .append(count)
                   .append(" Methoden\n");
        }

        // Footer / Trenner
        builder.append("\n---\n");
        builder.append("_Generated by RSEV Controller Mod_\n");

        // Datei schreiben (überschreibt bestehende Datei)
        Files.writeString(indexFile, builder.toString());
    }

    /**
     * Privater Konstruktor verhindert Instanziierung.
     */
    private LuaIndexGenerator() {}
}