package de.rsev.minecraft.forge.controller.lua.bridge.assets;

import de.rsev.minecraft.forge.controller.lua.LuaRuntime;
import de.rsev.minecraft.forge.controller.lua.tools.datapack.DataPackWriter;
import de.rsev.minecraft.forge.controller.lua.tools.datapack.LootTableGenerator;
import org.luaj.vm2.LuaError;
import org.luaj.vm2.LuaTable;
import org.luaj.vm2.LuaValue;
import org.luaj.vm2.Varargs;
import org.luaj.vm2.lib.OneArgFunction;
import org.luaj.vm2.lib.ThreeArgFunction;
import org.luaj.vm2.lib.TwoArgFunction;
import org.luaj.vm2.lib.VarArgFunction;
import org.luaj.vm2.lib.ZeroArgFunction;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.StringJoiner;
import java.util.regex.Pattern;

public final class LuaAssetsBridge {

    private static final Pattern VALID_NAME = Pattern.compile("[a-z0-9._-]+");
    private static final int DEFAULT_PACK_FORMAT = 15;
    private static final String MARKER_FILE = ".minecraft-lua-controller";

    public static LuaTable create() {
        LuaTable assets = new LuaTable();

        assets.set("root", new ZeroArgFunction() {
            @Override
            public LuaValue call() {
                return LuaValue.valueOf(generatedDataPacksRoot().toString());
            }
        });

        assets.set("createPack", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                String packName = sanitizePackName(args.checkjstring(1));
                String description = args.narg() >= 2 ? args.checkjstring(2) : "Generated by minecraft-lua-controller";
                int packFormat = args.narg() >= 3 ? args.checkint(3) : DEFAULT_PACK_FORMAT;

                try {
                    return LuaValue.valueOf(ensurePack(packName, description, packFormat).toString());
                } catch (IOException e) {
                    throw new LuaError("Assets.createPack failed: " + e.getMessage());
                }
            }
        });

        assets.set("clearPack", new OneArgFunction() {
            @Override
            public LuaValue call(LuaValue arg) {
                String packName = sanitizePackName(arg.checkjstring());
                try {
                    deleteRecursively(packRoot(packName));
                } catch (IOException e) {
                    throw new LuaError("Assets.clearPack failed: " + e.getMessage());
                }
                return LuaValue.NIL;
            }
        });

        assets.set("write", new ThreeArgFunction() {
            @Override
            public LuaValue call(LuaValue packArg, LuaValue relativeArg, LuaValue contentArg) {
                String packName = sanitizePackName(packArg.checkjstring());
                String relativePath = normalizeRelativePath(relativeArg.checkjstring());
                String content = contentArg.checkjstring();

                try {
                    ensurePack(packName, "Generated by minecraft-lua-controller", DEFAULT_PACK_FORMAT);
                    DataPackWriter.write(packRoot(packName), relativePath, content);
                } catch (IOException e) {
                    throw new LuaError("Assets.write failed: " + e.getMessage());
                }

                return LuaValue.NIL;
            }
        });

        assets.set("writeFunction", new ThreeArgFunction() {
            @Override
            public LuaValue call(LuaValue packArg, LuaValue targetArg, LuaValue contentArg) {
                String[] target = splitTarget(targetArg.checkjstring(), "function");
                String relative = "data/%s/functions/%s.mcfunction".formatted(target[0], target[1]);
                return assets.get("write").call(packArg, LuaValue.valueOf(relative), contentArg);
            }
        });

        assets.set("writeLootTable", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                String packName = sanitizePackName(args.checkjstring(1));
                String namespace = args.checkjstring(2);
                String path = args.checkjstring(3);
                String json = args.checkjstring(4);

                try {
                    ensurePack(packName, "Generated by minecraft-lua-controller", DEFAULT_PACK_FORMAT);
                    String relative = "data/%s/loot_tables/%s.json".formatted(namespace, path);
                    DataPackWriter.write(packRoot(packName), relative, json);
                } catch (IOException e) {
                    throw new LuaError("Assets.writeLootTable failed: " + e.getMessage());
                }

                return LuaValue.NIL;
            }
        });

        assets.set("writeRecipe", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                String packName = sanitizePackName(args.checkjstring(1));
                String namespace = args.checkjstring(2);
                String path = args.checkjstring(3);
                String json = args.checkjstring(4);

                try {
                    ensurePack(packName, "Generated by minecraft-lua-controller", DEFAULT_PACK_FORMAT);
                    String relative = "data/%s/recipes/%s.json".formatted(namespace, path);
                    DataPackWriter.write(packRoot(packName), relative, json);
                } catch (IOException e) {
                    throw new LuaError("Assets.writeRecipe failed: " + e.getMessage());
                }

                return LuaValue.NIL;
            }
        });

        assets.set("writeAdvancement", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                String packName = sanitizePackName(args.checkjstring(1));
                String namespace = args.checkjstring(2);
                String path = args.checkjstring(3);
                String json = args.checkjstring(4);

                try {
                    ensurePack(packName, "Generated by minecraft-lua-controller", DEFAULT_PACK_FORMAT);
                    String relative = "data/%s/advancements/%s.json".formatted(namespace, path);
                    DataPackWriter.write(packRoot(packName), relative, json);
                } catch (IOException e) {
                    throw new LuaError("Assets.writeAdvancement failed: " + e.getMessage());
                }

                return LuaValue.NIL;
            }
        });

        assets.set("writePredicate", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                String packName = sanitizePackName(args.checkjstring(1));
                String namespace = args.checkjstring(2);
                String path = args.checkjstring(3);
                String json = args.checkjstring(4);

                try {
                    ensurePack(packName, "Generated by minecraft-lua-controller", DEFAULT_PACK_FORMAT);
                    String relative = "data/%s/predicates/%s.json".formatted(namespace, path);
                    DataPackWriter.write(packRoot(packName), relative, json);
                } catch (IOException e) {
                    throw new LuaError("Assets.writePredicate failed: " + e.getMessage());
                }

                return LuaValue.NIL;
            }
        });

        assets.set("writeTag", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                String packName = sanitizePackName(args.checkjstring(1));
                String registryType = args.checkjstring(2);
                String namespace = args.checkjstring(3);
                String path = args.checkjstring(4);
                String json = args.checkjstring(5);

                try {
                    ensurePack(packName, "Generated by minecraft-lua-controller", DEFAULT_PACK_FORMAT);
                    String relative = "data/%s/tags/%s/%s.json".formatted(namespace, registryType, path);
                    DataPackWriter.write(packRoot(packName), relative, json);
                } catch (IOException e) {
                    throw new LuaError("Assets.writeTag failed: " + e.getMessage());
                }

                return LuaValue.NIL;
            }
        });

        assets.set("simpleChestLoot", new TwoArgFunction() {
            @Override
            public LuaValue call(LuaValue itemIdArg, LuaValue countArg) {
                return LuaValue.valueOf(LootTableGenerator.generateSimpleChestLoot(
                        itemIdArg.checkjstring(),
                        countArg.checkint()
                ));
            }
        });

        assets.set("shapelessRecipe", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                String resultItem = args.checkjstring(1);
                int resultCount = args.checkint(2);
                if (args.narg() < 3) {
                    throw new LuaError("Assets.shapelessRecipe requires at least one ingredient");
                }

                StringJoiner ingredients = new StringJoiner(",\n      ");
                for (int i = 3; i <= args.narg(); i++) {
                    ingredients.add("""
                            {
                              "item": "%s"
                            }
                            """.formatted(args.checkjstring(i)).indent(6).trim());
                }

                String json = """
                        {
                          "type": "minecraft:crafting_shapeless",
                          "ingredients": [
                            %s
                          ],
                          "result": {
                            "item": "%s",
                            "count": %d
                          }
                        }
                        """.formatted(ingredients, resultItem, resultCount);

                return LuaValue.valueOf(json);
            }
        });

        assets.set("smeltingRecipe", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                String inputItem = args.checkjstring(1);
                String resultItem = args.checkjstring(2);
                float experience = (float) args.checkdouble(3);
                int cookingTime = args.narg() >= 4 ? args.checkint(4) : 200;

                String json = """
                        {
                          "type": "minecraft:smelting",
                          "ingredient": {
                            "item": "%s"
                          },
                          "result": "%s",
                          "experience": %s,
                          "cookingtime": %d
                        }
                        """.formatted(inputItem, resultItem, trimTrailingZeros(experience), cookingTime);

                return LuaValue.valueOf(json);
            }
        });

        assets.set("itemTag", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                if (args.narg() < 1) {
                    throw new LuaError("Assets.itemTag requires at least one value");
                }
                return LuaValue.valueOf(buildTagJson(false, args));
            }
        });

        assets.set("blockTag", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                if (args.narg() < 1) {
                    throw new LuaError("Assets.blockTag requires at least one value");
                }
                return LuaValue.valueOf(buildTagJson(false, args));
            }
        });

        assets.set("entityTypeTag", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                if (args.narg() < 1) {
                    throw new LuaError("Assets.entityTypeTag requires at least one value");
                }
                return LuaValue.valueOf(buildTagJson(false, args));
            }
        });

        assets.set("predicateMatchTool", new OneArgFunction() {
            @Override
            public LuaValue call(LuaValue itemArg) {
                String json = """
                        {
                          "condition": "minecraft:match_tool",
                          "predicate": {
                            "items": [
                              "%s"
                            ]
                          }
                        }
                        """.formatted(itemArg.checkjstring());
                return LuaValue.valueOf(json);
            }
        });

        assets.set("locationBlockPredicate", new OneArgFunction() {
            @Override
            public LuaValue call(LuaValue blockArg) {
                String json = """
                        {
                          "condition": "minecraft:location_check",
                          "predicate": {
                            "block": {
                              "blocks": [
                                "%s"
                              ]
                            }
                          }
                        }
                        """.formatted(blockArg.checkjstring());
                return LuaValue.valueOf(json);
            }
        });

        assets.set("impossibleAdvancement", new VarArgFunction() {
            @Override
            public Varargs invoke(Varargs args) {
                String title = args.checkjstring(1);
                String description = args.checkjstring(2);
                String iconItem = args.checkjstring(3);
                String rewardFunction = args.narg() >= 4 ? args.checkjstring(4) : null;

                String rewards = rewardFunction == null
                        ? ""
                        : """
                          ,
                          "rewards": {
                            "function": "%s"
                          }
                        """.formatted(rewardFunction);

                String json = """
                        {
                          "display": {
                            "icon": {
                              "item": "%s"
                            },
                            "title": "%s",
                            "description": "%s",
                            "frame": "task",
                            "announce_to_chat": false,
                            "show_toast": false,
                            "hidden": true
                          },
                          "criteria": {
                            "generated": {
                              "trigger": "minecraft:impossible"
                            }
                          }%s
                        }
                        """.formatted(
                        iconItem,
                        escapeJson(title),
                        escapeJson(description),
                        rewards
                );

                return LuaValue.valueOf(json);
            }
        });

        return assets;
    }

    private static Path generatedDataPacksRoot() {
        Path root = LuaRuntime.getLuaGeneratedDataPacksDir();
        if (root == null) {
            throw new LuaError("Assets bridge unavailable: generated datapack root is null");
        }
        return root;
    }

    private static Path packRoot(String packName) {
        return generatedDataPacksRoot().resolve(packName);
    }

    private static Path ensurePack(String packName, String description, int packFormat) throws IOException {
        Path root = packRoot(packName);
        Files.createDirectories(root);
        Files.writeString(root.resolve(MARKER_FILE), "generated\n");
        writePackMeta(root, description, packFormat);
        return root;
    }

    private static void writePackMeta(Path root, String description, int packFormat) throws IOException {
        String escapedDescription = description
                .replace("\\", "\\\\")
                .replace("\"", "\\\"");
        String packMeta = """
                {
                  "pack": {
                    "pack_format": %d,
                    "description": "%s"
                  }
                }
                """.formatted(packFormat, escapedDescription);
        Files.writeString(root.resolve("pack.mcmeta"), packMeta);
    }

    private static String sanitizePackName(String packName) {
        String normalized = packName.trim().toLowerCase().replace(' ', '-');
        if (normalized.isBlank() || !VALID_NAME.matcher(normalized).matches()) {
            throw new LuaError("Invalid pack name: " + packName);
        }
        return normalized;
    }

    private static String normalizeRelativePath(String relativePath) {
        String normalized = relativePath.replace('\\', '/');
        if (normalized.startsWith("/") || normalized.contains("..")) {
            throw new LuaError("Invalid asset path: " + relativePath);
        }
        return normalized;
    }

    private static String buildTagJson(boolean replace, Varargs args) {
        StringJoiner values = new StringJoiner(",\n    ");
        for (int i = 1; i <= args.narg(); i++) {
            values.add("\"" + escapeJson(args.checkjstring(i)) + "\"");
        }

        return """
                {
                  "replace": %s,
                  "values": [
                    %s
                  ]
                }
                """.formatted(replace, values);
    }

    private static String trimTrailingZeros(float value) {
        if (value == (long) value) {
            return Long.toString((long) value);
        }
        return Float.toString(value);
    }

    private static String escapeJson(String input) {
        return input
                .replace("\\", "\\\\")
                .replace("\"", "\\\"");
    }

    private static String[] splitTarget(String target, String kind) {
        String[] parts = target.split(":", 2);
        if (parts.length != 2 || parts[0].isBlank() || parts[1].isBlank()) {
            throw new LuaError("Invalid " + kind + " target: " + target + " expected namespace:path");
        }
        return parts;
    }

    private static void deleteRecursively(Path root) throws IOException {
        if (!Files.exists(root)) {
            return;
        }

        try (var stream = Files.walk(root)) {
            stream.sorted(Comparator.reverseOrder()).forEach(path -> {
                try {
                    Files.deleteIfExists(path);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            });
        } catch (RuntimeException e) {
            if (e.getCause() instanceof IOException ioException) {
                throw ioException;
            }
            throw e;
        }
    }

    private LuaAssetsBridge() {}
}
