modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="minecraft_lua_controller"
version="${version}"
displayName="RSEV Lua Controller"
description='''
Lua runtime controller mod
'''

[[dependencies.minecraft_lua_controller]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.minecraft_lua_controller]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
