-- lua/load/example.lua
-- Executed once during controller startup.
-- Generates a simple datapack that is mirrored into the active world's datapacks folder.

local pack = "lua-example-assets"

Assets.createPack(pack, "Example assets generated by minecraft-lua-controller")

local loot = Assets.simpleChestLoot("minecraft:diamond", 3)
Assets.writeLootTable(pack, "minecraft", "chests/lua_example_bonus", loot)

Assets.writeFunction(pack, "minecraft:lua_example_ping", [[
say Lua-generated datapack function loaded successfully.
]])

System.print("Loading VM generated datapack assets in " .. LUA_GENERATED_DATAPACKS_DIR)
